
import React, { useState } from 'react';
import { ProjectDeliverables, AGENTS, Scene } from '../types';
import { Clock, Video, Mic, FileText, CheckCircle, Compass, Layout, Database, Download, Copy, Image as ImageIcon, Edit3, Save, Plus, Trash, X, ExternalLink } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Props {
  data: ProjectDeliverables;
  isLoading: boolean;
  onUpdate: (newData: ProjectDeliverables) => void;
}

const ProjectDeliverablesView: React.FC<Props> = ({ data, isLoading, onUpdate }) => {
  const [activeTab, setActiveTab] = useState<'strategy' | 'script' | 'data'>('strategy');
  const [isEditing, setIsEditing] = useState(false);

  // --- PDF GENERATION ---
  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.text("Project Bible / 视频策划全案", 14, 22);
    doc.setFontSize(10);
    doc.text(`Generated by DreamCrew AI - ${new Date().toLocaleDateString()}`, 14, 30);
    
    let yPos = 40;

    // 1. Strategy Section
    doc.setFontSize(16);
    doc.setTextColor(100, 100, 255);
    doc.text("1. Strategic Plan (战略策划)", 14, yPos);
    yPos += 10;
    
    const strategyData = [
      ["Core Values", data.strategicPlan.coreValues],
      ["Narrative", data.strategicPlan.narrativeStructure],
      ["Logic Flow", data.strategicPlan.logicFlow]
    ];

    autoTable(doc, {
      startY: yPos,
      head: [['Section', 'Content']],
      body: strategyData,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229] },
      columnStyles: { 0: { cellWidth: 40, fontStyle: 'bold' } },
      styles: { overflow: 'linebreak' }, 
    });

    // 2. Script Section
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(16);
    doc.setTextColor(100, 100, 255);
    doc.text(`2. Script & Shots (分镜脚本 - 共 ${data.script.length} 镜)`, 14, finalY);

    const scriptBody = data.script.map(scene => [
        `#${scene.sceneNumber}\n${scene.duration}`,
        `${scene.shotType}\n${scene.transition}`,
        `VISUAL: ${scene.visual}\n\nMJ PROMPT: ${scene.midjourneyPrompt}`,
        `AUDIO: ${scene.audio}`
    ]);

    autoTable(doc, {
      startY: finalY + 10,
      head: [['Shot', 'Tech Spec', 'Visual / MJ Prompt', 'Audio']],
      body: scriptBody,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229] },
      columnStyles: {
        0: { cellWidth: 15 },
        1: { cellWidth: 25 },
        2: { cellWidth: 90 },
        3: { cellWidth: 50 }
      },
      styles: { fontSize: 8, overflow: 'linebreak', valign: 'top' }
    });

    // 3. Data Verification
    const finalY2 = (doc as any).lastAutoTable.finalY + 15;
    doc.text("3. Data Verification (数据核实)", 14, finalY2);
    
    const dataBody = data.dataVerification.map(d => [d.fact, d.source + (d.url ? `\n[${d.url}]` : ''), d.status]);
    
    autoTable(doc, {
        startY: finalY2 + 10,
        head: [['Fact', 'Source / Link', 'Status']],
        body: dataBody,
        theme: 'striped'
    });

    doc.save("project_script_bible.pdf");
  };

  // --- EDIT HANDLERS ---
  const handleStrategyChange = (field: keyof typeof data.strategicPlan, value: string) => {
      onUpdate({
          ...data,
          strategicPlan: { ...data.strategicPlan, [field]: value }
      });
  };

  const handleScriptChange = (idx: number, field: keyof Scene, value: any) => {
      const newScript = [...data.script];
      newScript[idx] = { ...newScript[idx], [field]: value };
      onUpdate({ ...data, script: newScript });
  };

  const addScene = () => {
      const newScene: Scene = {
          id: Math.random().toString(36).substr(2,9),
          sceneNumber: data.script.length + 1,
          shotType: '中景',
          transition: '切',
          visual: '在此输入新的分镜画面描述...',
          midjourneyPrompt: 'New scene prompt...',
          audio: '在此输入旁白...',
          interaction: '',
          duration: '3s'
      };
      onUpdate({ ...data, script: [...data.script, newScene] });
  };

  const removeScene = (idx: number) => {
      if(!window.confirm("确定删除此镜头吗？")) return;
      const newScript = data.script.filter((_, i) => i !== idx).map((s, i) => ({ ...s, sceneNumber: i + 1 }));
      onUpdate({ ...data, script: newScript });
  };
  
  const handleDataChange = (idx: number, field: string, value: string) => {
     const newDataVer = [...data.dataVerification];
     (newDataVer[idx] as any)[field] = value;
     onUpdate({ ...data, dataVerification: newDataVer });
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-gray-400 animate-pulse space-y-4 p-12">
        <Layout className="w-16 h-16 opacity-50 text-brand-500" />
        <div className="text-center">
             <h3 className="text-xl font-bold text-white mb-2">正在生成项目全案...</h3>
             <ul className="text-sm space-y-1 text-gray-500">
                <li>总策划正在梳理叙事结构...</li>
                <li>资深策划正在撰写对白 (20+ 镜头)...</li>
                <li>体验设计师正在细化分镜与Midjourney提示词...</li>
                <li>调研员正在核实数据来源与链接...</li>
             </ul>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-gray-850 rounded-xl shadow-xl overflow-hidden border border-gray-750 flex flex-col h-full w-full">
      {/* Header Tabs */}
      <div className="bg-gray-900 border-b border-gray-800 px-6 pt-4 flex items-center justify-between shrink-0">
         <div className="flex space-x-1 overflow-x-auto">
            <button onClick={() => setActiveTab('strategy')} className={`px-4 py-3 text-sm font-medium rounded-t-lg flex items-center transition-colors whitespace-nowrap ${activeTab === 'strategy' ? 'bg-gray-800 text-brand-400 border-t-2 border-brand-500' : 'text-gray-500 hover:text-gray-300'}`}>
                <Compass className="w-4 h-4 mr-2" /> 战略 (Plan)
            </button>
            <button onClick={() => setActiveTab('script')} className={`px-4 py-3 text-sm font-medium rounded-t-lg flex items-center transition-colors whitespace-nowrap ${activeTab === 'script' ? 'bg-gray-800 text-brand-400 border-t-2 border-brand-500' : 'text-gray-500 hover:text-gray-300'}`}>
                <FileText className="w-4 h-4 mr-2" /> 脚本 (Script) <span className="ml-1 text-[10px] bg-gray-700 px-1.5 rounded-full text-gray-300">{data.script.length}</span>
            </button>
            <button onClick={() => setActiveTab('data')} className={`px-4 py-3 text-sm font-medium rounded-t-lg flex items-center transition-colors whitespace-nowrap ${activeTab === 'data' ? 'bg-gray-800 text-brand-400 border-t-2 border-brand-500' : 'text-gray-500 hover:text-gray-300'}`}>
                <Database className="w-4 h-4 mr-2" /> 数据 (Data)
            </button>
         </div>
         
         <div className="flex space-x-2 pb-2">
            <button 
                onClick={() => setIsEditing(!isEditing)}
                className={`text-xs px-3 py-1.5 rounded border transition-colors flex items-center font-bold ${
                    isEditing 
                    ? 'bg-yellow-600/20 text-yellow-500 border-yellow-500' 
                    : 'bg-gray-800 text-gray-300 border-gray-600 hover:border-gray-400'
                }`}
            >
                {isEditing ? <><Save className="w-3 h-3 mr-1" /> 完成编辑</> : <><Edit3 className="w-3 h-3 mr-1" /> 编辑模式</>}
            </button>
            <button 
                onClick={downloadPDF}
                className="text-xs bg-brand-700 hover:bg-brand-600 text-white px-3 py-1.5 rounded border border-brand-500 transition-colors flex items-center whitespace-nowrap"
            >
                <Download className="w-3 h-3 mr-1" /> PDF
            </button>
         </div>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-auto bg-gray-900/50 p-6">
        
        {/* TAB 1: STRATEGY */}
        {activeTab === 'strategy' && (
            <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn">
                <div className="bg-gray-800 p-6 rounded-lg border border-gray-700 shadow-lg relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-32 h-32 bg-purple-500/10 rounded-bl-full -mr-10 -mt-10"></div>
                    <div className="flex items-center mb-4 text-purple-400">
                        <Compass className="w-6 h-6 mr-3" />
                        <h3 className="text-xl font-bold">核心价值观 (Core Values)</h3>
                    </div>
                    {isEditing ? (
                        <textarea 
                            className="w-full h-32 bg-gray-900 border border-gray-600 rounded p-3 text-gray-200 focus:ring-2 focus:ring-brand-500 outline-none"
                            value={data.strategicPlan.coreValues}
                            onChange={(e) => handleStrategyChange('coreValues', e.target.value)}
                        />
                    ) : (
                        <div className="text-gray-200 leading-relaxed whitespace-pre-wrap">
                            <ReactMarkdown>{data.strategicPlan.coreValues}</ReactMarkdown>
                        </div>
                    )}
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="bg-gray-800 p-6 rounded-lg border border-gray-700 shadow-lg">
                        <div className="flex items-center mb-4 text-brand-400">
                            <Layout className="w-5 h-5 mr-2" />
                            <h3 className="text-lg font-bold">叙事结构 (Structure)</h3>
                        </div>
                        {isEditing ? (
                            <textarea 
                                className="w-full h-64 bg-gray-900 border border-gray-600 rounded p-3 text-sm text-gray-200 focus:ring-2 focus:ring-brand-500 outline-none"
                                value={data.strategicPlan.narrativeStructure}
                                onChange={(e) => handleStrategyChange('narrativeStructure', e.target.value)}
                            />
                        ) : (
                            <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">
                                <ReactMarkdown>{data.strategicPlan.narrativeStructure}</ReactMarkdown>
                            </div>
                        )}
                    </div>
                    <div className="bg-gray-800 p-6 rounded-lg border border-gray-700 shadow-lg">
                        <div className="flex items-center mb-4 text-brand-400">
                            <Video className="w-5 h-5 mr-2" />
                            <h3 className="text-lg font-bold">展项逻辑 (Logic Flow)</h3>
                        </div>
                        {isEditing ? (
                            <textarea 
                                className="w-full h-64 bg-gray-900 border border-gray-600 rounded p-3 text-sm text-gray-200 focus:ring-2 focus:ring-brand-500 outline-none"
                                value={data.strategicPlan.logicFlow}
                                onChange={(e) => handleStrategyChange('logicFlow', e.target.value)}
                            />
                        ) : (
                            <div className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">
                                <ReactMarkdown>{data.strategicPlan.logicFlow}</ReactMarkdown>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        )}

        {/* TAB 2: SCRIPT */}
        {activeTab === 'script' && (
            <div className="space-y-4 animate-fadeIn max-w-6xl mx-auto">
                {isEditing && (
                    <div className="flex justify-end mb-4">
                        <button onClick={addScene} className="flex items-center px-4 py-2 bg-green-600 hover:bg-green-500 text-white rounded shadow text-sm font-bold">
                            <Plus className="w-4 h-4 mr-2" /> 添加新镜头
                        </button>
                    </div>
                )}

                {data.script.map((scene, idx) => (
                <div key={scene.id} className={`bg-gray-800 rounded-lg border overflow-hidden group transition-all ${isEditing ? 'border-yellow-500/30' : 'border-gray-700 hover:border-brand-500/50'}`}>
                    
                    <div className="flex flex-col md:flex-row relative">
                         {isEditing && (
                             <button onClick={() => removeScene(idx)} className="absolute top-2 right-2 text-gray-500 hover:text-red-500 z-10">
                                 <X className="w-4 h-4" />
                             </button>
                         )}

                        {/* 1. Technical Info Column */}
                        <div className="md:w-32 bg-gray-900/50 p-4 border-b md:border-b-0 md:border-r border-gray-700 flex flex-col justify-center text-center space-y-2">
                            <span className="text-brand-500 font-mono font-bold text-2xl">#{scene.sceneNumber}</span>
                            
                            {isEditing ? (
                                <>
                                    <input 
                                        className="w-full bg-gray-950 text-xs border border-gray-600 rounded p-1 text-center text-white" 
                                        value={scene.duration}
                                        onChange={(e) => handleScriptChange(idx, 'duration', e.target.value)}
                                        placeholder="Duration"
                                    />
                                    <input 
                                        className="w-full bg-gray-950 text-xs border border-gray-600 rounded p-1 text-center text-white" 
                                        value={scene.shotType}
                                        onChange={(e) => handleScriptChange(idx, 'shotType', e.target.value)}
                                        placeholder="Shot Type"
                                    />
                                    <input 
                                        className="w-full bg-gray-950 text-xs border border-gray-600 rounded p-1 text-center text-white" 
                                        value={scene.transition}
                                        onChange={(e) => handleScriptChange(idx, 'transition', e.target.value)}
                                        placeholder="Transition"
                                    />
                                </>
                            ) : (
                                <>
                                    <div className="text-xs text-gray-400 flex items-center justify-center"><Clock className="w-3 h-3 mr-1" /> {scene.duration}</div>
                                    <div className="px-2 py-1 bg-gray-800 rounded text-[10px] text-gray-300 border border-gray-700 whitespace-nowrap overflow-hidden text-ellipsis">{scene.shotType}</div>
                                    <div className="px-2 py-1 bg-gray-800 rounded text-[10px] text-gray-400 border border-gray-700 whitespace-nowrap overflow-hidden text-ellipsis">{scene.transition}</div>
                                </>
                            )}
                        </div>

                        {/* 2. Visual & Prompt Column */}
                        <div className="flex-1 p-5 border-b md:border-b-0 md:border-r border-gray-700">
                            <h4 className="flex items-center text-xs uppercase tracking-wider text-gray-500 font-semibold mb-2">
                                <Video className="w-3 h-3 mr-1" /> 画面分镜 (Visual)
                            </h4>
                            
                            {isEditing ? (
                                <textarea
                                    className="w-full h-24 bg-gray-900 border border-gray-600 rounded p-2 text-sm text-white mb-2"
                                    value={scene.visual}
                                    onChange={(e) => handleScriptChange(idx, 'visual', e.target.value)}
                                />
                            ) : (
                                <div className="text-gray-200 text-sm leading-relaxed mb-4">
                                    <ReactMarkdown>{scene.visual}</ReactMarkdown>
                                </div>
                            )}
                            
                            {/* MJ Prompt Box */}
                            <div className="bg-black/30 rounded border border-gray-700/50 p-3 relative group/prompt">
                                <div className="flex items-center text-[10px] text-purple-400 font-bold mb-1">
                                    <ImageIcon className="w-3 h-3 mr-1" /> MIDJOURNEY PROMPT
                                </div>
                                {isEditing ? (
                                    <textarea
                                        className="w-full h-16 bg-gray-900/50 border border-gray-600 rounded p-1 text-xs font-mono text-gray-300"
                                        value={scene.midjourneyPrompt}
                                        onChange={(e) => handleScriptChange(idx, 'midjourneyPrompt', e.target.value)}
                                    />
                                ) : (
                                    <code className="text-xs text-gray-400 font-mono break-all block">
                                        {scene.midjourneyPrompt}
                                    </code>
                                )}
                                {!isEditing && (
                                    <button 
                                        onClick={() => navigator.clipboard.writeText(scene.midjourneyPrompt)}
                                        className="absolute top-2 right-2 p-1 hover:bg-white/10 rounded text-gray-500 hover:text-white transition-colors"
                                        title="Copy Prompt"
                                    >
                                        <Copy className="w-3 h-3" />
                                    </button>
                                )}
                            </div>
                        </div>

                        {/* 3. Audio & Interaction Column */}
                        <div className="md:w-1/3 flex flex-col">
                            <div className="flex-1 p-5 border-b border-gray-700 bg-gray-800/20">
                                <h4 className="flex items-center text-xs uppercase tracking-wider text-gray-500 font-semibold mb-2">
                                    <Mic className="w-3 h-3 mr-1" /> 对白/VO (Audio)
                                </h4>
                                {isEditing ? (
                                    <textarea
                                        className="w-full h-32 bg-gray-900 border border-gray-600 rounded p-2 text-sm text-white italic"
                                        value={scene.audio}
                                        onChange={(e) => handleScriptChange(idx, 'audio', e.target.value)}
                                    />
                                ) : (
                                    <div className="text-white font-serif text-sm leading-relaxed italic pl-3 border-l-2 border-brand-500/50">
                                        <ReactMarkdown>{scene.audio}</ReactMarkdown>
                                    </div>
                                )}
                            </div>
                            <div className="p-4 bg-green-900/5">
                                <h4 className="flex items-center text-xs uppercase tracking-wider text-green-600/70 font-semibold mb-1">
                                    <Layout className="w-3 h-3 mr-1" /> 交互 (Interaction)
                                </h4>
                                {isEditing ? (
                                    <input
                                        className="w-full bg-gray-900 border border-gray-600 rounded p-1 text-xs text-green-100"
                                        value={scene.interaction}
                                        onChange={(e) => handleScriptChange(idx, 'interaction', e.target.value)}
                                    />
                                ) : (
                                    <div className="text-green-100/70 text-xs leading-relaxed">
                                        {scene.interaction}
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
                ))}
            </div>
        )}

        {/* TAB 3: DATA */}
        {activeTab === 'data' && (
            <div className="max-w-5xl mx-auto space-y-4 animate-fadeIn">
                 <div className="bg-blue-900/10 border border-blue-500/20 p-4 rounded-lg flex items-start gap-3 mb-6">
                    <div className="p-2 bg-blue-500/20 rounded-lg">
                        <img src={AGENTS.Researcher.avatar} className="w-8 h-8 rounded-full" />
                    </div>
                    <div>
                        <h4 className="text-blue-400 font-bold">来自 {AGENTS.Researcher.name} 的数据校核报告</h4>
                        <p className="text-xs text-blue-300/70 mt-1">所有引用的技术参数和行业背景均已根据专业数据库进行比对。请重点核查带有 "Needs Check" 标记的项目。</p>
                    </div>
                 </div>

                 <div className="bg-gray-800 rounded-lg border border-gray-700 overflow-hidden">
                    <table className="w-full text-left text-sm text-gray-400">
                        <thead className="bg-gray-900 text-gray-200 uppercase font-medium">
                            <tr>
                                <th className="px-6 py-3 w-1/3">核查点 (Fact)</th>
                                <th className="px-6 py-3 w-1/3">专业出处 / 来源 (Source)</th>
                                <th className="px-6 py-3 w-1/6 text-center">状态 (Status)</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-700">
                            {data.dataVerification.map((item, idx) => (
                                <tr key={idx} className="hover:bg-gray-700/50">
                                    <td className="px-6 py-4 text-white align-top">
                                        {isEditing ? (
                                            <textarea 
                                                className="w-full bg-gray-900 border border-gray-600 rounded p-1 text-white"
                                                rows={2}
                                                value={item.fact}
                                                onChange={(e) => handleDataChange(idx, 'fact', e.target.value)}
                                            />
                                        ) : item.fact}
                                    </td>
                                    <td className="px-6 py-4 align-top">
                                        {isEditing ? (
                                            <>
                                                <input 
                                                    className="w-full bg-gray-900 border border-gray-600 rounded p-1 text-brand-300 mb-1"
                                                    value={item.source}
                                                    onChange={(e) => handleDataChange(idx, 'source', e.target.value)}
                                                    placeholder="Source Name"
                                                />
                                                <input 
                                                    className="w-full bg-gray-900 border border-gray-600 rounded p-1 text-gray-400 text-xs"
                                                    value={item.url || ''}
                                                    onChange={(e) => handleDataChange(idx, 'url', e.target.value)}
                                                    placeholder="URL"
                                                />
                                            </>
                                        ) : (
                                            <div>
                                                <div className="font-medium text-brand-200">{item.source}</div>
                                                {item.url && (
                                                    <a 
                                                        href={item.url} 
                                                        target="_blank" 
                                                        rel="noopener noreferrer" 
                                                        className="text-xs text-brand-500 hover:text-brand-400 flex items-center mt-1 break-all"
                                                    >
                                                        <ExternalLink className="w-3 h-3 mr-1 flex-shrink-0" />
                                                        {item.url}
                                                    </a>
                                                )}
                                            </div>
                                        )}
                                    </td>
                                    <td className="px-6 py-4 text-center align-top">
                                         {isEditing ? (
                                            <select
                                                className="bg-gray-900 border border-gray-600 rounded p-1 text-xs"
                                                value={item.status}
                                                onChange={(e) => handleDataChange(idx, 'status', e.target.value)}
                                            >
                                                <option value="Verified">Verified</option>
                                                <option value="Needs Check">Needs Check</option>
                                            </select>
                                        ) : (
                                            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                                                item.status === 'Verified' ? 'bg-green-900 text-green-300' : 'bg-yellow-900 text-yellow-300'
                                            }`}>
                                                <CheckCircle className="w-3 h-3 mr-1" /> {item.status}
                                            </span>
                                        )}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                 </div>
            </div>
        )}

      </div>
    </div>
  );
};

export default ProjectDeliverablesView;
